# Site settings
title: Matthew DeCicco
email: deciccomatthew@gmail.com
url: https://github.com/SpaceninjaMatt/portfolio
description: "A collection of some of my more notable projects."
keywords: "Mechanical Engineering, Computer Engineering, Electrical Engineering, Student, Florida Polytechnic University"
degree: "Bachelor of Science in Mechanical Engineering with a concentration in Aerospace"
graduation: "May 2024"
skills: "Solidworks Certified(CSWA) - Programming Experience(Python•C/C++) - Avid Learner"
meta_author: DeCicco Matthew

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 532d8e #80B3FF
  primary-rgb: "83, 45, 142" #"128,179,255"
  secondary: B1B3B5 #FD6E8A
  secondary-dark: 6f7173 #A2122F

# Footer settings
footer:
  copyright: Matthew DeCicco
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/matthew-j-decicco/
  - title: github
    url: http://github.com/SpaceninjaMatt

# Postal address (add as many lines as necessary)
address:
  - line: 411 Mirrorton Ave
  - line: Lakeland, FL 33801

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
